# Generated by Django 5.0 on 2025-04-18 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('manuel', 'Manuel'), ('automatique', 'Automatique')], max_length=20)),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id_produit', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('format', models.CharField(max_length=255)),
                ('ingredients', models.TextField()),
                ('stock_actuel', models.CharField(max_length=255)),
                ('exp_date', models.DateField()),
                ('status', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('categorie', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('debut_week', models.DateField()),
                ('prediction', models.FloatField()),
                ('id_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mon_app.produit')),
            ],
        ),
        migrations.CreateModel(
            name='ContenuPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mon_app.pack')),
                ('id_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mon_app.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
                ('responsable', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=255)),
                ('id_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mon_app.produit')),
            ],
        ),
    ]
